### 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [5]:
print(np.version.version)

1.17.2


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
* Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [15]:
a = np.random.random((2,3,5))

### 4. Print a.

In [11]:
print(a)

[[[0.33205605 0.04754665 0.2199339  0.64457256 0.75400436]
  [0.83147742 0.95507176 0.15601678 0.99632707 0.79376691]
  [0.44759567 0.30075135 0.91565363 0.71237504 0.11536292]]

 [[0.17377791 0.92489693 0.20322719 0.34696963 0.82959518]
  [0.50531773 0.15275151 0.85868985 0.60167021 0.54943977]
  [0.23398041 0.02498141 0.93249905 0.33765924 0.11527469]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [12]:
b = np.ones((5,3,2))

### 6. Print b.

In [13]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


### 7. Do a and b have the same size? How do you prove that in Python code?

In [16]:
print(len(a) == len(b))

False


### 8. Are you able to add a and b? Why or why not?

In [19]:
#Although both arrays have the same number of elements they vary in shape so addition is not possible

### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [21]:
c = np.transpose(b)

### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [22]:
d = a+c

In [23]:
#As both arrays have the same shape it's possible to add them
print(d)

[[[1.3134988  1.22822981 1.00124614 1.2170239  1.75265749]
  [1.29823148 1.37515291 1.09842278 1.06375011 1.42685899]
  [1.35636318 1.84982297 1.60670835 1.46260875 1.29340425]]

 [[1.61152823 1.05731737 1.20880567 1.3362162  1.21601514]
  [1.7010969  1.53537087 1.64971689 1.07012293 1.88643528]
  [1.49796927 1.64609133 1.92076018 1.78754824 1.59710999]]]


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
#Array d has all values as they are in array a plus 1, as a+c = d and c is a array full of 1
print(a)
print("\n")
print(d)

[[[0.3134988  0.22822981 0.00124614 0.2170239  0.75265749]
  [0.29823148 0.37515291 0.09842278 0.06375011 0.42685899]
  [0.35636318 0.84982297 0.60670835 0.46260875 0.29340425]]

 [[0.61152823 0.05731737 0.20880567 0.3362162  0.21601514]
  [0.7010969  0.53537087 0.64971689 0.07012293 0.88643528]
  [0.49796927 0.64609133 0.92076018 0.78754824 0.59710999]]]


[[[1.3134988  1.22822981 1.00124614 1.2170239  1.75265749]
  [1.29823148 1.37515291 1.09842278 1.06375011 1.42685899]
  [1.35636318 1.84982297 1.60670835 1.46260875 1.29340425]]

 [[1.61152823 1.05731737 1.20880567 1.3362162  1.21601514]
  [1.7010969  1.53537087 1.64971689 1.07012293 1.88643528]
  [1.49796927 1.64609133 1.92076018 1.78754824 1.59710999]]]


### 12. Multiply a and c. Assign the result to e.

In [27]:
e = a*c

### 13. Does e equal to a? Why or why not?

In [28]:
#It's not equal because multiplication and addition have different outputs in almost every single case
print(e)

[[[0.3134988  0.22822981 0.00124614 0.2170239  0.75265749]
  [0.29823148 0.37515291 0.09842278 0.06375011 0.42685899]
  [0.35636318 0.84982297 0.60670835 0.46260875 0.29340425]]

 [[0.61152823 0.05731737 0.20880567 0.3362162  0.21601514]
  [0.7010969  0.53537087 0.64971689 0.07012293 0.88643528]
  [0.49796927 0.64609133 0.92076018 0.78754824 0.59710999]]]


### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [51]:
d_min = np.min(d)
d_mean = np.mean(d)
d_max = np.max(d)
print(d_min, d_mean, d_max)

1.0012461398180301 1.4355361468977261 1.920760179719501


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [47]:
f = np.empty((2,3,5))
print(f)

[[[0.3134988  0.22822981 0.00124614 0.2170239  0.75265749]
  [0.29823148 0.37515291 0.09842278 0.06375011 0.42685899]
  [0.35636318 0.84982297 0.60670835 0.46260875 0.29340425]]

 [[0.61152823 0.05731737 0.20880567 0.3362162  0.21601514]
  [0.7010969  0.53537087 0.64971689 0.07012293 0.88643528]
  [0.49796927 0.64609133 0.92076018 0.78754824 0.59710999]]]



### 16. Populate the values in f.
For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [56]:
i = 0
for array2d in d:
    j = 0
    for array1d in array2d:
        k = 0
        for value in array1d:
            if value > d_min and value < d_mean: f[i,j,k] = 25
            elif value > d_mean and value < d_max: f[i,j,k] = 75
            elif value == d_min: f[i,j,k] = 0
            elif value == d_mean: f[i,j,k] = 50
            elif value == d_max: f[i,j,k] = 100
            k += 1
        j += 1
    i += 1

### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [57]:
#I got the expected f!
print(d)
print("\n")
print(f)

[[[1.3134988  1.22822981 1.00124614 1.2170239  1.75265749]
  [1.29823148 1.37515291 1.09842278 1.06375011 1.42685899]
  [1.35636318 1.84982297 1.60670835 1.46260875 1.29340425]]

 [[1.61152823 1.05731737 1.20880567 1.3362162  1.21601514]
  [1.7010969  1.53537087 1.64971689 1.07012293 1.88643528]
  [1.49796927 1.64609133 1.92076018 1.78754824 1.59710999]]]


[[[ 25.  25.   0.  25.  75.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 75.  75. 100.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""


In [76]:
g = []
i = 0
for array2d in d:
    g.append([])
    j = 0
    for array1d in array2d:
        g[i].append([])
        k = 0
        for value in array1d:
            if value > d_min and value < d_mean: g[i][j].append('B')
            elif value > d_mean and value < d_max: g[i][j].append('D')
            elif value == d_min: g[i][j].append('A')
            elif value == d_mean: g[i][j].append('C')
            elif value == d_max: g[i][j].append('E')
            k += 1
        j += 1
    i += 1

In [77]:
print(g)

[[['B', 'B', 'A', 'B', 'D'], ['B', 'B', 'B', 'B', 'B'], ['B', 'D', 'D', 'D', 'B']], [['D', 'B', 'B', 'B', 'B'], ['D', 'D', 'D', 'B', 'D'], ['D', 'D', 'E', 'D', 'D']]]
